### ISSUE TITLE
切换控制器时存在一个手势冲突的bug

### ISSUE THREAD

**Issue by XWXGitHub** [qingfengiOS/QFMultipleScrollView#1]
当我把第一个控制器顶到最上面(即滑到headVw隐藏的时候)并且tab列表往上再滑动一段距离，这时我再点击第二个控制器，把headView向下拉离停靠点但不完全显示headVw，之后再切回第一个控制器，然后向下滑tab列表，这时底部SCrollerView和第一个控制器里的tabView下拉会一起滑动,手势就冲突了。

**Comment by qingfengiOS** [comment]
是的，有这个问题，多谢指正，可以在点击切换列表按钮的时候把子controller的偏移量设为0解决这个问题。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XWXGitHub <notifications@github.com&gt;
发送时间: 2020年6月11日 11:24
收件人: qingfengiOS/QFMultipleScrollView <QFMultipleScrollView@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[qingfengiOS/QFMultipleScrollView] 切换控制器时存在一个手势冲突的bug (#1)





 
当我把第一个控制器顶到最上面(即滑到headVw隐藏的时候)并且tab列表往上再滑动一段距离，这时我再点击第二个控制器，把headView向下拉离停靠点但不完全显示headVw，之后再切回第一个控制器，然后向下滑tab列表，这时底部SCrollerView和第一个控制器里的tabView下拉会一起滑动,手势就冲突了。

**Comment by XWXGitHub** [comment]
这种方法交互有点不太好，但是作品是好的，还得感谢你的共享。我也尝试着想更改那个问题，但是自己能力不足还做不到。期待你更多的优秀作品。

**Comment by qingfengiOS** [comment]
我们的业务需求就是那个样子的😂



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XWXGitHub <notifications@github.com&gt;
发送时间: 2020年6月12日 17:49
收件人: qingfengiOS/QFMultipleScrollView <QFMultipleScrollView@noreply.github.com&gt;
抄送: 情风 <291753906@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[qingfengiOS/QFMultipleScrollView] 切换控制器时存在一个手势冲突的bug (#1)





 
这种方法交互有点不太好，但是作品是好的，还得感谢你的共享。我也尝试着想更改那个问题，但是自己能力不足还做不到。期待你更多的优秀作品。

**Comment by XWXGitHub** [comment]
嗯是的。其实我想在你代码的基础上实现能达到停靠效果的同时保持底部两个控制的位置互不干扰，然后想了想好复杂，各种情况需要进行判断。
