### ISSUE TITLE
viewdidLoad 方法默认设置containerScrollView.contentOffset无效

### ISSUE THREAD

**Issue by EverYeon** [qingfengiOS/QFMultipleScrollView#2]
// MARK: - Life Cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        initBootomScrollView()
        initHeaderView()
        initPageTitleView()
        initSubControllers()
        
        containerScrollView.contentOffset = CGPoint(x: CGFloat(1.0) * Screen.width, y: 0.0)
    }

containerScrollView 不能自动切换到第二屏

**Comment by qingfengiOS** [comment]
在viewDidAppear里面可以生效，不过title的选中状态也需要处理一下，Demo比较粗糙
