### ISSUE TITLE
如果tableView需要下拉刷新怎么处理

### ISSUE THREAD

**Issue by tianxiawoyougood** [qingfengiOS/QFMultipleScrollView#3]
如果tableView需要下拉刷新怎么处理

**Comment by qingfengiOS** [comment]
在底层的scrollView上加刷新事件不就可以吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tianxiawoyougood <notifications@github.com&gt;
发送时间: 2020年8月18日 19:20
收件人: qingfengiOS/QFMultipleScrollView <QFMultipleScrollView@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[qingfengiOS/QFMultipleScrollView] 如果tableView需要下拉刷新怎么处理 (#3)





 
如果tableView需要下拉刷新怎么处理

**Comment by tianxiawoyougood** [comment]
产品的需求，tableView上面的view和tableView是两种内容，依赖两个接口。下拉只想更新tableView的内容。

**Comment by qingfengiOS** [comment]
这种交互方式好像还没在哪里见过呢，如果要做可能需要从最大偏移量思考

**Comment by tianxiawoyougood** [comment]
好的，谢谢。
